# Generated by Django 4.2.1 on 2023-05-16 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="employees",
            field=models.ManyToManyField(
                related_name="company_emps", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
