# Generated by Django 4.2.1 on 2023-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_company_employees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="employees",
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=250)),
                (
                    "company",
                    models.ManyToManyField(related_name="company", to="base.company"),
                ),
            ],
        ),
    ]
