# Generated by Django 4.2.1 on 2023-05-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_company_employees_usermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="company",
            field=models.ManyToManyField(related_name="users", to="base.company"),
        ),
    ]
