# Generated by Django 4.2.1 on 2023-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_usermodel_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
